import Head from 'next/head';
import React from 'react';
import { Accordion } from 'react-bootstrap';
import Navbar from '../../components/Navbar';
import { ElectionFrameworkLaws, ElectionFrameworkOverview, responsive } from '../../constants';

const ElectionLaws = () => {
  return (
    <div className='constitutional--provision--container'>
      <Head>
        <title>Election Related Laws</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <Navbar />
      <div className='flex justify-center mt-3 mb-5 px-3 lg:px-0'>
        <div className={`${responsive} flex flex-col justify-between rounded-1 flex-wrap lg:px-3`}>
          <h4 className='my-4'>Electoral Framework Overview</h4>
          {
            Object.keys(ElectionFrameworkLaws).map((key:string, i:number) => {
              return (
                <div className='my-3'>
                  <h4>{i+1}. {key}</h4>
                  <ul className='list-group'>
                    {ElectionFrameworkLaws[key].map((d:string, i:number) => {
                      return (<li key={i} className='list-group-item py-3'>{d}</li>)
                    })}
                  </ul>
                </div>
              )
            })
          }
        </div>
      </div>
    </div>
  )
}

export default ElectionLaws;
