import Head from 'next/head';
import React from 'react';
import Navbar from '../../components/Navbar';
import { ElectionFrameworkOverview, responsive } from '../../constants';

const Overview = () => {
  return (
    <div className='constitutional--provision--container'>
      <Head>
        <title>Privacy | Policy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <Navbar />
      <div className='flex justify-center mt-3 mb-5 px-3 lg:px-0'>
        <div className={`${responsive} flex flex-col justify-between rounded-1 flex-wrap lg:px-3`}>
          <h4 className='my-3'>Electoral Framework Overview</h4>
          <ul className='list-group'>
            {ElectionFrameworkOverview.map((d:string, i:number) => {
              return (<li key={i} className='list-group-item py-3'>{d}</li>)
            })}
          </ul>
        </div>
      </div>
    </div>
  )
}

export default Overview;
