import { useState, useEffect } from 'react';
import Head from 'next/head';
import { GoPrimitiveDot } from 'react-icons/go';
import Navbar from '../components/Navbar';
import LiveCounterCard from '../components/LiveCounterCard/LiveCounterCard';
import electionChannel from "../services/pusher-events";
import { getCandidateList } from '../utils';
import { useSelector } from 'react-redux';
import { PROVINCE } from '../constants';
import _ from 'lodash';

export default function Home() {
  const [electionStatus, setElectionStatus] = useState("");
  const [candidateList, setCandidateList] = useState([]);
  const { electionData } = useSelector((state: any) => state.electionReducer);

  useEffect(() => {
    (async () => {
      const candidateList = await getCandidateList();
      setCandidateList(candidateList);
    })();
  }, []);


  const electionCandidates = _.groupBy(candidateList, candidate => candidate.user.province);
  const electionCandidatesArray = Object.entries(electionCandidates);

  electionChannel.bind("start-election-event", () => {
    console.log("election started");
    setElectionStatus("start")
  });

  electionChannel.bind("end-election-event", () => {
    console.log("election ended");
    setElectionStatus("end")
  });

  return (
    <div>
      <Head>
        <title>DAPP VOTING</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <Navbar />
      <div className='px-4 py-3 flex justify-center mt-1'>
        <div>
          <div className='lg:w-[1100px] w-full lg:px-2 max-[1100px]:px-1'>
            <div className='flex items-center'>
              <span className='text-2xl font-bold text-black'>Hot Seats</span>
              <GoPrimitiveDot className={`text-4xl ml-5 mr-1 ${electionStatus === 'start' && "text-danger"}`} />
              <span className='text-[17px]'>{
                !electionStatus ? "NO ELECTION" : (electionStatus === "start" ? "LIVE" : "ENDED")
              }</span>
            </div>
          </div>
          <div className='lg:w-[1100px] flex justify-around flex-wrap'>
            {electionData && electionCandidatesArray.length > 0 && electionCandidatesArray?.map(([key, value]: any) =>
              <LiveCounterCard type={key} data={value} key={key} electionStatus={electionStatus} />)}
          </div>
        </div>
      </div>
    </div>
  )
}
