import { useEffect, useState } from 'react';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import ElectionCard from '../components/LiveCounterCard/ElectionCard';
import { Carousel } from '@trendyol-js/react-carousel';
import { getElectionList } from '../utils';
import _ from 'lodash';
import { getStorage } from '../services';
import Marquee from 'react-fast-marquee';
import { FaRegNewspaper } from 'react-icons/fa';
import { BsChevronLeft, BsChevronRight } from 'react-icons/bs';
import { Fade } from 'react-slideshow-image';
import 'react-slideshow-image/dist/styles.css';
import 'animate.css';
import moment from 'moment';

export default function Home() {
  const [electionLists, setElectionLists] = useState([]);
  const loggedInAccountAddress = getStorage("loggedInAccountAddress");
  const [countDown, setCountDown] = useState({ days: 0, hours: 0, minutes: 0, seconds: 0 });
  const [timer, setTimer] = useState({ id: "seconds", play: false });
  const [showSlideCount, setShowSlideCount] = useState(4);

  useEffect(() => {
    (async () => {
      const electionList = await getElectionList();
      setElectionLists(electionList);
    })();

    window.addEventListener('resize', (e) => {
      window.innerWidth > 1080 && setShowSlideCount(3.5)
      window.innerWidth <= 1080 && setShowSlideCount(3)
      window.innerWidth <= 1060 && setShowSlideCount(2.5)
      window.innerWidth <= 900 && setShowSlideCount(2)
      window.innerWidth <= 500 && setShowSlideCount(1.5)
      window.innerWidth <= 400 && setShowSlideCount(1)
    })

    return () => {
      window.removeEventListener("resize", null);
    }
  }, []);

  if (electionLists.length > 0) {
    const { startDate, endDate } = electionLists.at(-1);
    if (new Date() < new Date(startDate)) {
      setInterval(() => {
        const diff = new Date(startDate).getTime() - new Date().getTime();
        const days = Math.floor(diff / (1000 * 60 * 60 * 24));
        const hours = Math.floor((diff % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
        const minutes = Math.floor((diff % (1000 * 60 * 60)) / (1000 * 60));
        const seconds = Math.floor((diff % (1000 * 60)) / 1000);
        setCountDown({ ...countDown, days, hours, minutes, seconds })
      }, 1000);
    }
  }

  useEffect(() => {
    setTimer({ id: "days", play: true });
    setTimeout(() => {
      setTimer({ id: "days", play: false });
    }, 950);
  }, [countDown.days]);

  useEffect(() => {
    setTimer({ id: "hours", play: true });
    setTimeout(() => {
      setTimer({ id: "hours", play: false });
    }, 950);
  }, [countDown.hours]);

  useEffect(() => {
    setTimer({ id: "minutes", play: true });
    setTimeout(() => {
      setTimer({ id: "minutes", play: false });
    }, 950);
  }, [countDown.minutes]);

  useEffect(() => {
    setTimer({ id: "seconds", play: true });
    setTimeout(() => {
      setTimer({ id: "seconds", play: false });
    }, 900);
  }, [countDown.seconds]);

  return (
    <div>
      <Head>
        <title>DAPP VOTING</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <Navbar />
      <div className='px-4 py-3 flex justify-center'>
        <div className='flex flex-column justify-between'>
          <div className='lg:w-[1065px] w-[100vw] overflow-hidden'>
            <div className='flex items-center'>
              <div className='w-full flex'>
                <div className='shrink-0 w-[170px] px-3 py-[5px] flex items-center bg-red-600 rounded-tr-[10px] text-slate-100 shadow-inner'>
                  <FaRegNewspaper className='text-2xl mr-2' />
                  Latest update
                </div>
                <Marquee pauseOnHover={true} gradient={false} className="tracking-wider text-blue-900">
                  निर्वाचनका सम्पूर्ण गतिविधिहरूलाई आम जनताको सहज पहुँचसम्म पुर्याउन निर्वाचन आयोग अन्तर्गत ७ वटा प्रदेशमा प्रदेश निर्वाचन कार्यालय रहेका छन जसमा नेपाल सरकारको प्रशासन सेवा, सामान्य प्रशासन समूह, राजपत्रांकित द्वित्तीय श्रेणीको प्रदेश निर्वाचन अधिकारी कार्यालय प्रमुखका रूपमा रहने व्यवस्था गरिएको छ । सम्बन्धित प्रदेश निर्वाचन कार्यालयको वेबसाइटमा जानको लागि प्रदेश छनौट गर्नुहोस :
                </Marquee>
              </div>
            </div>

            <div className='mt-3 w-[100vw] lg:h-[400px] sm:h-[300px] md:rounded-t-[5px] sm:rounded-0 overflow-hidden'>
              <Fade
                autoplay={true}
                nextArrow={<BsChevronRight className='absolute text-slate-100 text-4xl' />}
                prevArrow={<BsChevronLeft className='absolute text-slate-100 text-4xl' />}>
                <img className='lg:h-[400px] h-[300px] w-[100vw] object-cover transition ease-in-out delay-[500px] hover:scale-125 hover:opacity-100' src="/images/banner1.jpeg" />
                <img className='lg:h-[400px] h-[300px] w-[100vw] object-cover transition ease-in-out delay-[500px] hover:scale-125 hover:opacity-100' src="/images/banner2.jpeg" />
                <img className='lg:h-[400px] h-[300px] w-[100vw] object-cover transition ease-in-out delay-[500px] hover:scale-125 hover:opacity-100' src="/images/banner3.jpeg" />
                <img className='lg:h-[400px] h-[300px] w-[100vw] object-cover transition ease-in-out delay-[500px] hover:scale-125 hover:opacity-100' src="/images/banner4.jpeg" />
                <img className='lg:h-[400px] h-[300px] w-[100vw] object-cover transition ease-in-out delay-[500px] hover:scale-125 hover:opacity-100' src="/images/banner5.jpeg" />
                <img className='lg:h-[400px] h-[300px] w-[100vw] object-cover transition ease-in-out delay-[500px] hover:scale-125 hover:opacity-100' src="/images/banner6.jpeg" />
                <img className='lg:h-[400px] h-[300px] w-[100vw] object-cover transition ease-in-out delay-[500px] hover:scale-125 hover:opacity-100' src="/images/banner7.jpeg" />
              </Fade>
            </div>

            <div>
              <div className='countdown_timer py-4 my-3 min-h-[320px] sm:h-fit bg-[url("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkkyoysDz8fhLil6JB1VlqOh08zd-h2emhWw&usqp=CAU")] rounded-1 text-slate-100 flex flex-column items-center'>
                <h3 className='my-4 mb-3 text-slate-300 text-center'>Election Nepal 2024 Happening</h3>
                <div className='flex justify-evenly flex-wrap lg:w-[70vw] mt-3'>
                  <div className='days lg:w-[140px] sm:w-[100px] mx-3 text-center'>
                    <h5 className='my-3 text-slate-300'>DAYS</h5>
                    <div className='px-0 lg:py-[10px] sm:py-2 lg:text-8xl sm:text-7xl bg-black card__box__shadow rounded-1 countdown_timer_count overflow-hidden'>
                      <div className={`animate__animated ${timer.id === "days" && timer.play && "animate__slideInUp"}`}>{countDown.days}</div>
                    </div>
                  </div>
                  <div className='days lg:w-[140px] sm:w-[100px] mx-3 text-center'>
                    <h5 className='my-3 text-slate-300'>HOURSE</h5>
                    <div className='px-0 lg:py-[10px] sm:py-2 lg:text-8xl sm:text-7xl bg-black card__box__shadow rounded-1 countdown_timer_count overflow-hidden'>
                      <div className={`animate__animated ${timer.id === "hours" && timer.play && "animate__slideInUp"}`}>{countDown.hours}</div>
                    </div>
                  </div>
                  <div className='days lg:w-[140px] sm:w-[100px] mx-3 text-center'>
                    <h5 className='my-3 text-slate-300'>MINUTES</h5>
                    <div className='px-0 lg:py-[10px] sm:py-2 lg:text-8xl sm:text-7xl bg-black card__box__shadow rounded-1 countdown_timer_count overflow-hidden'>
                      <div className={`animate__animated ${timer.id === "minutes" && timer.play && "animate__slideInUp"}`}>{countDown.minutes}</div>
                    </div>
                  </div>
                  <div className='days lg:w-[140px] sm:w-[100px] mx-3 text-center'>
                    <h5 className='my-3 text-slate-300'>SECONDS</h5>
                    <div className='px-0 lg:py-[10px] sm:py-2 lg:text-8xl sm:text-7xl bg-black card__box__shadow rounded-1 countdown_timer_count overflow-hidden'>
                      <div className={`animate__animated ${timer.id === "seconds" && timer.play && "animate__slideInUp"}`}>{countDown.seconds}</div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div className='my-5'>
              <h4 className='font-bold'>Election Gallery</h4>
              <div className='flex justify-between'>
                <Carousel
                  className='pt-2 shadow-none'
                  show={showSlideCount - 1}
                  slide={showSlideCount}
                  transition={0.5}
                  infinite={true}
                  swiping={true}
                  responsive={true}
                >
                  <ElectionCard title={electionLists[0]} src={"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6TmGNICTnHT0loCNYhfHl19PNyeyoFwgWWA&usqp=CAU"} />
                  <ElectionCard title={electionLists[1]} src={"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRr7tAfxvSIht5RdzGToAQY4_-dijvGgxsXAg&usqp=CAU"} />
                  <ElectionCard title={electionLists[2]} src={"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVbKo5oeymz96MHktj8BTL5Ylyx-AhWVCe_Q&usqp=CAU"} />
                  <ElectionCard title={electionLists[3]} src={"https://static.pib.gov.in/WriteReadData/userfiles/image/image01342FU.jpg"} />
                </Carousel>
              </div>
            </div>


            <div className='my-4'>
              <h5 className='font-bold'>Overall Elections Data</h5>
              <div className='w-full'>

              </div>
            </div>

          </div>
        </div>
      </div>
    </div >
  )
}
