import { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import Head from 'next/head';
import { useDispatch, useSelector } from 'react-redux';
import Navbar from '../../../components/Navbar';
import electionChannel from "../../../services/pusher-events";
import { getCandidateList, getElectionList, getElectionStatus, getFormattedErrorMessage, getSortedCandidatesList, getVoterList } from '../../../utils';
import _ from 'lodash';
import { PROVINCE, SmartContract } from '../../../constants';
import { setCandidateList } from '../../../redux/reducers/candidateReducer';
import { toast } from 'react-toastify';
import UserCard from '../../../components/UserCard';
import { getVoterDetails } from '../../../utils/web3';

export default function Home({ provinceNo }) {
  const [electionStatus, setElectionStatus] = useState(null);
  const [electionList, setElectionList] = useState([]);
  const [candidateLists, setCandidateLists] = useState([]);
  const [currentElection, setCurrentElection] = useState<any>({});
  const loggedInAccountAddress = useSelector((state: any) => state.loggedInUserReducer.address);

  let voteCastEvent = null;

  const router = useRouter();
  const dispatch = useDispatch();

  useEffect(() => {
    (async () => {
      const electionList = await getElectionList();
      const candidateLists = await getCandidateList();
      const { currentElection, electionCandidatesArray } = getSortedCandidatesList(electionList, candidateLists);
      const electionStatus = getElectionStatus("Province", currentElection);

      setElectionStatus(electionStatus);
      setCandidateLists(electionCandidatesArray);
      setCurrentElection(currentElection);
      dispatch(setCandidateList(candidateLists));
      setElectionList(electionList);

      voteCastEvent = SmartContract.events.VoteCast().on("data", (event: any) => {
        const votedCandidateDetails = event.returnValues[0];
        let filterCandidates = candidateLists.map((d: any) => {
          return d.user._id === votedCandidateDetails.user._id ? { ...votedCandidateDetails } : { ...d };
        });
        const { electionCandidatesArray } = getSortedCandidatesList(electionList, filterCandidates);
        setCandidateLists(electionCandidatesArray);
      });
    })();

    return () => {
      voteCastEvent && voteCastEvent?.unsubscribe();
    }
  }, []);


  electionChannel.bind("start-election-event", () => {
    console.log("election started");
    setElectionStatus("LIVE");
  });

  electionChannel.bind("end-election-event", () => {
    console.log("election ended");
    setElectionStatus("ENDED")
  });


  const casteVote = async (_candidateID: string) => {
    try {
      // restrict voting before electin start and end


      const voterDetails = await getVoterDetails(loggedInAccountAddress);

      // vote limit count
      if (voterDetails.voteLimitCount === "3") return toast.info("You've exceed the vote limit count !");

      const casteCandidateDetails = _.find(candidateLists, (elections) => {
        elections[1].find(((candidate: any) => candidate.user._id === _candidateID))
      });
      const isAlreadyVoted = casteCandidateDetails?.votedVoterLists?.includes(loggedInAccountAddress);
      if (isAlreadyVoted) return toast.info("You've already casted vote !");

      // await SmartContract.methods.vote(_candidateID).send({ from: loggedInAccountAddress });
      toast.success("Vote caste successfully.");
    } catch (error) {
      console.log(error)
      toast.error(`Failed to caste vote !, ${getFormattedErrorMessage(error.message)}`, { toastId: 2 });
    }
  }

  const navigateTo = () => router.push("/election/province");

  const provinceIndex = provinceNo === 0 ? 0 : provinceNo - 1;

  return (
    <div>
      <Head>
        <title>Province Election</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <Navbar />
      <div className='px-4 py-3 flex justify-center mt-1'>
        <div className='flex flex-column justify-between'>

          {/* province level elections */}
          <div className='lg:w-[1100px] w-full lg:px-2 max-[1100px]:px-1'>

            <div className='flex items-center h-fit mt-3 mb-4'>
              <div className='w-fit py-1 pl-3 pr-10 mr-5 flex items-center bg-red-700 rounded-tr-full text-slate-100'>
                <span className='text-slate-100 mr-2 cursor-pointer' onClick={navigateTo}>Province</span> /
                <span className='text-slate-100 ml-2'>{PROVINCE[provinceIndex]?.label}</span>
              </div>
              <span className='ml-2 text-lg font-bold text-black'>Total Candidates: {candidateLists[provinceIndex] && (candidateLists[provinceIndex][1]?.length ?? 0)}</span>
            </div>

            {/* candidate lists */}
            <div className='flex flex-wrap justify-between'>
              {
                candidateLists[provinceIndex] ?
                  candidateLists[provinceIndex][1]?.map((candidateDetails: any, i) =>
                    <UserCard
                      details={candidateDetails}
                      type="candidate"
                      key={i}
                      currentElection={electionList[electionList.length - 1]}
                      casteVote={casteVote}
                    />) : "No Candidates Available !"
              }
            </div>

          </div>
        </div>
      </div>
    </div>
  )
}

export const getServerSideProps = async ({ params }) => {
  const { slug } = params;
  const provinceNo = parseInt(slug);

  if (isNaN(provinceNo)) {
    return {
      redirect: {
        permanent: false,
        destination: ""
      }
    }
  }

  return {
    props: { provinceNo }
  }
}