import Head from 'next/head';
import React from 'react';
import ElectionOfficeCard from '../../components/ElectionOfficeCard';
import Navbar from '../../components/Navbar';
import { responsive, StateProvinceOffices, DistrictOffices } from '../../constants';
import { useTranslations } from 'next-intl';

const Privacy = () => {
  const homepageT = useTranslations("homepage");
  const electionT = useTranslations("election_offices");

  return (
    <div className='constitutional--provision--container'>
      <Head>
        <title>{electionT("title")}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <Navbar />
      <div className='flex justify-center mt-3 mb-5 px-3 lg:px-0'>
        <div className={`${responsive} flex justify-between rounded-1 flex-wrap lg:px-3`}>
          <div>
            <h5 className='my-4'>{electionT("state_offices")}</h5>
            <div className='state--ofice flex flex-wrap justify-between'>
              {StateProvinceOffices
                && StateProvinceOffices.map((name, i) => <ElectionOfficeCard officeName={homepageT(`province${i + 1}`)} key={i} />)
              }
            </div>
          </div>
          <div className='my-3'>
            <h5 className='my-4'>{electionT("district_election_offices")}</h5>
            <div className='state--ofice flex flex-wrap justify-between'>
              {DistrictOffices
                && DistrictOffices.map((name, i) => <ElectionOfficeCard officeName={electionT(name.toLowerCase())} key={i} />)
              }
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Privacy;
