import Head from 'next/head';
import React from 'react';
import Navbar from '../../components/Navbar';
import { responsive } from '../../constants';
import { useTranslations } from 'next-intl';

const Privacy = () => {
  const t = useTranslations("privacy");

  return (
    <div className='constitutional--provision--container'>
      <Head>
        <title>{t("title")}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <Navbar />
      <div className='flex justify-center mt-3 mb-5 px-3 lg:px-0'>
        <div className={`${responsive} flex flex-col justify-between rounded-1 flex-wrap lg:px-3`}>
          <h4 className='my-3'>{t("title")}</h4>
          <p>{t("para1")}</p>
          <p>{t("para2")}</p>
          <p>{t("para3")}
            <a href='mailto:info@election.gov.np'> info@election.gov.np</a>
          </p><br /><br />
          <h5>{t("footer_title")}</h5>
        </div>
      </div>
    </div>
  )
}

export default Privacy;
